#
# Module manifest for module 'BinEnvPath'
#
# Generated by: Henrique do Val
#
# Generated on: 04/08/2025
#

@{
RootModule = 'envpath_msil.dll'
ModuleVersion = '0.0.1'
GUID = 'a848b7a1-c1e9-4845-84e2-e18d94132858'
Author = 'Henrique do Val'
CompanyName = 'Henrique do Val'
Copyright = '(c) Henrique do Val. All rights reserved.'

    ## Description of the functionality provided by this module
# Description = ''
    ## Minimum version of the PowerShell engine required by this module
# PowerShellVersion = ''
    ## Name of the PowerShell host required by this module
# PowerShellHostName = ''
    ## Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''
    ## Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

FunctionsToExport = @()
CmdletsToExport = @(
        "Test-EnvPath",
        "Update-EnvPath",
        "Add-EnvPath",
        "Remove-EnvPath"
)
VariablesToExport = '*'
AliasesToExport = @()
FileList = @("envpath.dll")

PrivateData = @{
    PSData = @{
        Tags = @("path", "environment", "variable", "update", "refresh")

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    }

}
}

