#
# Module manifest for module 'BinEnvPath'
#
# Generated by: Henrique do Val
#
# Generated on: 04/08/2025
#

@{
RootModule = 'envpath_msil.dll'
ModuleVersion = '0.0.2'
GUID = 'a848b7a1-c1e9-4845-84e2-e18d94132858'
Author = 'Henrique do Val'
CompanyName = 'Henrique do Val'
Copyright = '(c) Henrique do Val. All rights reserved.'

Description = 'Update Path environment variable for the current session. Diagnoses, adds and removes entries from path in registry'

FunctionsToExport = @()
CmdletsToExport = @(
        "Test-EnvPath",
        "Update-EnvPath",
        "Add-EnvPath",
        "Remove-EnvPath"
)
VariablesToExport = '*'
AliasesToExport = @()
FileList = @("envpath.dll")

PrivateData = @{
    PSData = @{
        Tags = @("path", "environment", "variable", "update", "refresh")
        LicenseUri = 'https://github.com/HenriquedoVal/envpath/blob/main/LICENSE'
        ProjectUri = 'https://github.com/HenriquedoVal/envpath'
    }
}
}
